# Notebook 07 - Sensitivity Analysis (Per-Layer + Per-Expert)

## Learning objective
Identify which parts of DeepSeek-Coder-V2-Lite-Instruct are most sensitive to quantization, so we can make principles mixed-precision decisions in Notebook 08.

## Key concepts
- **Sensitivity**: how much quality drops when a specific component is quantized while others stay higher precision.
- **Per-layer sensitivity**: some transformer blocks tolerate INT4 well, others cause large degredations
- **Per-expert sensitivity**: experts are not equally important; some may be much more fragile under quantization
- **Ablation thinking**: change one component at a time, measure effect, rank impact.
- **Heatmap interpretation**: darker/higher values = larger performance drop = more precision-sensitive component.

## Impact
This is the core intellectual step of the project: moving from "INT4 vs INT8 comparison" to "which internal components actually drive that gap."

## Inputs from previous notebooks
- `results/03_baseline_evaluation.json` (FP16 quality reference)
- `results/05_ptq_artifacts_summary.json` (quantized artifact metadata)
- `results/06_benchmarksing_perf_snapshot.json` (cross-precision speed/memory context)

## Outputs we will produce
- Layer sensitivity table + ranked list
- Expert sensitivity table + ranked list
- Layer/expert heatmaps saved to `results/`
- A recommended precision policy for Notebook 08

# TODO
- [ ] Clean up imports.  No duplicates
- [ ] Refactor repeated code chunks to functions, where appropriate
- [ ] Add explicit memory management after compute-heavy cells

In [1]:
# Imports
from transformers import AutoTokenizer, AutoModelForCausalLM
from pathlib import Path
from llama_cpp import Llama                                                                                              
from datasets import load_dataset
import pandas as pd
import datetime as dt
import numpy as np
import json
import gc
import time
import re

In [ ]:
# Setup: load benchmark context from Notebook 06
ROOT = Path.cwd().resolve().parent
RESULTS_DIR = ROOT / "results"
BENCHMARK_PATH = RESULTS_DIR / "06_benchmarking_perf_snapshot.json"

with BENCHMARK_PATH.open() as f:
    bench = json.load(f)

metadata = bench["benchmark_results"]["metadata"]
artifacts = bench["benchmark_results"]["artifacts"]
measurements = bench["benchmark_results"]["measurements"]

summary_rows = []

for precision, artifact_info in artifacts.items():
    perf = measurements.get(precision, {}).get("performance", {})
    mem = measurements.get(precision, {}).get("memory", {})
    summary_rows.append(
        {
            "precision": precision,
            "artifact_size_gib": artifact_info.get("artifact_size_gib"),
            "tokens_per_sec_mean": perf.get("tokens_per_sec_mean"),
            "ttft_sec_mean": perf.get("ttft_sec_mean"),
            "peak_rs_gib": mem.get("peak_rss_gib"),
        }
    )

benchmark_summary_df = pd.DataFrame(summary_rows).sort_values("artifact_size_gib", ascending=False)

print(f"Loaded benchmark run: {metadata.get('run_id')}")
print(f"Model: {metadata.get('model_id')}")
display(benchmark_summary_df)

Loaded benchmark run: 202604d06T025654Z
Model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct

,precision,artifact_size_gib,tokens_per_sec_mean,ttft_sec_mean,peak_rs_gib
0,fp16,29.27,74.738630,0.056434,29.451981
1,q8_0,15.56,114.013102,0.050479,38.823807
2,q4_k_m,9.66,137.556743,0.041548,9.443710

Load baseline references and define one shared sensitivity metric for this notebook.
Higher delta means more quantization damage relative to fp16 baseline

In [3]:
BASELINE_PATH = RESULTS_DIR / "03_baseline_evaluation.json"
EXPLORATION_PATH = RESULTS_DIR / "01_model_exploration.json"

with BASELINE_PATH.open() as f:
    baseline = json.load(f)
with EXPLORATION_PATH.open() as f:
    arch = json.load(f)

baseline_pass1 = float(baseline["summary"]["pass_at_1_percent"])
n_humaneval = int(baseline["summary"]["n_total"])
fp16_tps = float(bench["benchmark_results"]["measurements"]["fp16"]["performance"]["tokens_per_sec_mean"])

def sensitivity_delta_pass1(candidate_pass1_percent: float, reference_pass1_percent: float = baseline_pass1) -> float:
    return float(reference_pass1_percent - candidate_pass1_percent)

def sensitivity_rel_drop(candidate_pass1_percent: float, reference_pass1_percent: float = baseline_pass1) -> float:
    if reference_pass1_percent == 0:
        return np.nan
    return float((reference_pass1_percent - candidate_pass1_percent) / reference_pass1_percent)

context_df = pd.DataFrame(
    [
        {"metric": "baseline_pass@1_percent", "value": baseline_pass1},
        {"metric": "humaneval_n_problems", "value": n_humaneval},
        {"metric": "fp16_tokens_per_sec_mean", "value": fp16_tps},
        {"metric": "num_layers", "value": int(arch["num_layers"])},
        {"metric": "num_moe_layers", "value": len(arch["moe_layers"])},
        {"metric": "n_routed_experts", "value": int(arch["n_routed_experts"])},
        {"metric": "n_shared_experts", "value": int(arch["n_shared_experts"])},
    ]
)

display(context_df)

                     metric       value
0   baseline_pass@1_percent   60.365854
1      humaneval_n_problems  164.000000
2  fp16_tokens_per_sec_mean   74.738630
3                num_layers   27.000000
4            num_moe_layers   26.000000
5          n_routed_experts   64.000000
6          n_shared_experts    2.000000

Build a first-pass ablation manifest (coarse layer sweeep + expert sample sweep) for Notebook 07
We start coarse to map the landscape, then refine around the most sensitive regions

In [6]:
num_layers = int(arch["num_layers"])
moe_layers = list(map(int, arch["moe_layers"]))
n_routed_experts = int(arch["n_routed_experts"])

n_layer_groups = 9
layer_groups = np.array_split(np.arange(num_layers), n_layer_groups)

layer_manifest = []
for i, group in enumerate(layer_groups):
    layer_manifest.append(
        {
            "ablation_id": f"layer_group_{i:02d}",
            "kind": "layer_group",
            "target_layers": [int(x) for x in group.tolist()],
            "target_experts": None,
            "quantize_to": "q4_k_m",
            "keep_rest_as": "fp16",
            "status": "pending",
            "candidate_pass_at_1_percent": None,
            "delta_pass_at_1_percent": None,
            "relative_drop": None,
            "notes": "",
        }
    )

# first pass over every 4th routed expert across all MoE layers
expert_stride = 4
expert_sample_ids = list(range(0, n_routed_experts, expert_stride))

expert_manifest = []
for expert_id in expert_sample_ids:
    expert_manifest.append(
        {
            "ablation_id": f"expert_{expert_id:02d}_across_all_moe_layers",
            "kind": "expert_across_layers",
            "target_layers": moe_layers,
            "target_experts": [int(expert_id)],
            "quantize_to": "q4_k_m",
            "keep_rest_as": "fp16",
            "status": "pending",
            "candidate_pass_at_1_percent": None,
            "delta_pass_at_1_percent": None,
            "relative_drop": None,
            "notes": "",
        }
    )

manifest = {
    "timestamp_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
    "notebook": "07_sensitivity_analysis",
    "model_id": baseline["metadata"]["model_id"],
    "reference": {
        "baseline_pass_at_1_percent": baseline_pass1,
        "baseline_source": str(BASELINE_PATH),
    },
    "design": {
        "phase_1_layer_groups": n_layer_groups,
        "phase_1_expert_stride": expert_stride,
        "phase_2_rule": "Refine around top-3 most sensitive layer groups and top-8 most sensitive experts from phase 1.",
    },
    "ablations": {
        "layer": layer_manifest,
        "expert": expert_manifest,
    },
}

MANIFEST_PATH = RESULTS_DIR / "07_sensitivity_manifest.json"
with MANIFEST_PATH.open("w") as f:
    json.dump(manifest, f, indent=2)

print(f"Wrote manifest scaffold: {MANIFEST_PATH}")
print(f"Layer ablations: {len(layer_manifest)} | Expert ablations: {len(expert_manifest)}")

preview_df = pd.DataFrame(layer_manifest[:3] + expert_manifest[:3])[
    ["ablation_id", "kind", "quantize_to", "status"]
]
display(preview_df)

Wrote manifest scaffold: /Users/jarrett/dev/quantization-study/results/07_sensitivity_manifest.json
Layer ablations: 9 | Expert ablations: 16

                       ablation_id                  kind quantize_to   status
0                   layer_group_00           layer_group      q4_k_m  pending
1                   layer_group_01           layer_group      q4_k_m  pending
2                   layer_group_02           layer_group      q4_k_m  pending
3  expert_00_across_all_moe_layers  expert_across_layers      q4_k_m  pending
4  expert_04_across_all_moe_layers  expert_across_layers      q4_k_m  pending
5  expert_08_across_all_moe_layers  expert_across_layers      q4_k_m  pending

Claim the next pending ablation and define a helper to record its measured pass@1.

This keeps the manifest as the single source of truth for run status and sensitivity deltas.

In [7]:
with MANIFEST_PATH.open() as f:
    manifest = json.load(f)

baseline_pass1 = float(manifest["reference"]["baseline_pass_at_1_percent"])

all_items = manifest["ablations"]["layer"] + manifest["ablations"]["expert"]
pending = [a for a in all_items if a["status"] == "pending"]

if not pending:
    print("No pending ablations left.")
    current = None
else:
    current = pending[0]
    current["status"] = "in_progress"
    current["started_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()
    with MANIFEST_PATH.open("w") as f:
        json.dump(manifest, f, indent=2)

    print("Claimed ablation:")
    print(f"   id:            {current['ablation_id']}")
    print(f"   kind:          {current['kind']}")
    print(f"   target_layers: {current['target_layers']}")
    print(f"   target_experts:{current['target_experts']}")
    print(f"   quantize_to:   {current['quantize_to']}")
    print("")
    print("After you run evaluation for this ablation, call:")
    print("record_ablation_result(candidate_pass1_percent=<float>, notes='<optional>')")

def record_ablation_result(candidate_pass1_percent: float, notes: str = ""):
    with MANIFEST_PATH.open() as f:
        m = json.load(f)

    target = None
    for section in ["layer", "expert"]:
        for a in m["ablations"][section]:
            if a.get("status") == "in_progress":
                target = a
                break
        if target is not None:
            break
    
    if target is None:
        raise RuntimeError("No ablation is currently in_progress.")
    
    candidate = float(candidate_pass1_percent)
    delta = baseline_pass1 - candidate
    rel_drop = (delta / baseline_pass1) if baseline_pass1 else None

    target["candidate_pass_at_1_percent"] = candidate
    target["delta_pass_at_1_percent"] = delta
    target["relative_drop"] = rel_drop
    target["status"] = "completed"
    target["completed_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()
    if notes:
        target["notes"] = notes

    with MANIFEST_PATH.open("w") as f:
        json.dump(m, f, indent=2)

    print("Recorded result:")
    print(f"  id: {target['ablation_id']}")
    print(f"  candidate_pass@1: {candidate:.4f}")
    print(f"  delta_pass@1:     {delta:.4f}")
    print(f"  relative_drop:    {rel_drop:.4%}" if rel_drop is not None else "  relative_drop:    None")

Claimed ablation:
   id:            layer_group_00
   kind:          layer_group
   target_layers: [0, 1, 2]
   target_experts:None
   quantize_to:   q4_k_m

After you run evaluation for this ablation, call:
record_ablation_result(candidate_pass1_percent=<float>, notes='<optional>')

Heavy cell: load model/tokenizer once for Notebook 7 eval.

In [8]:
BASELINE_PATH = ROOT / "results" / "03_baseline_evaluation.json"

with BASELINE_PATH.open() as f:
    baseline = json.load(f)

model_id = baseline["metadata"]["model_id"]

if "tokenizer" not in globals():
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)

if "model" not in globals():
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype="auto",
        low_cpu_mem_usage=True,
    )
    model.eval()

print(f"Loaded tokenizer/model for: {model_id}")

`rope_parameters`'s factor field must be a float >= 1, got 40
`rope_parameters`'s beta_fast field must be a float, got 32
`rope_parameters`'s beta_slow field must be a float, got 1
`rope_parameters`'s factor field must be a float >= 1, got 40
`rope_parameters`'s beta_fast field must be a float, got 32
`rope_parameters`'s beta_slow field must be a float, got 1

Loading weights:   0%|          | 0/351 [00:00<?, ?it/s]

Loaded tokenizer/model for: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct

Run HumanEval for the currently in-progress ablation and compute candidate_pass1_percent.

Requres notebook-03 evaluation functions to already exist in this kernel (evaluate_problem + dependencies)

In [9]:
# Need to reset path to import helper functions
import sys                                                                                                               
from pathlib import Path                                                                                                 
                                                                                                                        
PROJECT_ROOT = Path.cwd().resolve().parent  # notebook is in notebooks/, root is one level up                            
if str(PROJECT_ROOT) not in sys.path:                                                                                    
    sys.path.insert(0, str(PROJECT_ROOT))

from utils.humaneval_helpers import evaluate_problem, clean_and_extract, execute_with_timeout

# Reset original root
ROOT = Path.cwd().resolve().parent

In [10]:
with MANIFEST_PATH.open() as f:
    manifest = json.load(f)

active = None
for section in ["layer", "expert"]:
    for a in manifest["ablations"][section]:
        if a.get("status") == "in_progress":
            active = a
            break
    if active is not None:
        break

if active is None:
    raise RuntimeError("No ablation is in_progress. Claim one first.")

humaneval = load_dataset("openai/openai_humaneval", split="test")
max_problems = 164 # set smaller (e.g. 20) for quick smoke test
subset = humaneval.select(range(min(max_problems, len(humaneval))))

ablation_results = []
t0 = time.time()

for i, problem in enumerate(subset, start=1):
    p0 = time.time()
    r = evaluate_problem(problem, model=model, tokenizer=tokenizer)
    elapsed = time.time() - p0
    r["elapsed_sec"] = elapsed
    ablation_results.append(r)

    if i % 10 == 0 or i == len(subset):
        n_pass = sum(1 for x in ablation_results if x["result"] == "passed")
        print(f"[{i:3d}/{len(subset)}] running pass rate: {100*n_pass/i:.2f}%")

total_elapsed = time.time() - t0
n_total = len(ablation_results)
n_passed = sum(1 for r in ablation_results if r["result"] == "passed")
candidate_pass1_percent = 100.0 * n_passed / n_total

out = {
    "timestamp_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
    "ablation_id": active["ablation_id"],
    "n_total": n_total,
    "n_passed": n_passed,
    "candidate_pass_at_1_percent": candidate_pass1_percent,
    "runtime_sec_total": total_elapsed,
    "results": ablation_results,
}
out_path = RESULTS_DIR / f"07_{active['ablation_id']}_humaneval.json"
with out_path.open("w") as f:
    json.dump(out, f, indent=2)

print("\nDone.")
print(f"ablation_id: {active['ablation_id']}")
print(f"candidate_pass1_percent: {candidate_pass1_percent:.6f}")
print(f"saved: {out_path}")
print("\nNow run:")
print(f"record_ablation_result(candidate_pass1_percent={candidate_pass1_percent:.6f}, notes='full HumanEval run')")

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[ 10/164] running pass rate: 50.00%
[ 20/164] running pass rate: 65.00%
[ 30/164] running pass rate: 70.00%
[ 40/164] running pass rate: 67.50%
[ 50/164] running pass rate: 70.00%
[ 60/164] running pass rate: 65.00%
[ 70/164] running pass rate: 62.86%
[ 80/164] running pass rate: 63.75%
[ 90/164] running pass rate: 63.33%
[100/164] running pass rate: 62.00%
[110/164] running pass rate: 60.91%
[120/164] running pass rate: 57.50%
[130/164] running pass rate: 53.85%
[140/164] running pass rate: 50.00%
[150/164] running pass rate: 50.00%
[160/164] running pass rate: 50.00%
[164/164] running pass rate: 49.39%

Done.
ablation_id: layer_group_00
candidate_pass1_percent: 49.390244
saved: /Users/jarrett/dev/quantization-study/results/07_layer_group_00_humaneval.json

Now run:
record_ablation_result(candidate_pass1_percent=49.390244, notes='full HumanEval run')

In [11]:
record_ablation_result(candidate_pass1_percent=49.390244, notes='full HumanEval run')

Recorded result:
  id: layer_group_00
  candidate_pass@1: 49.3902
  delta_pass@1:     10.9756
  relative_drop:    18.1818%

#### Setting up the pipeline
Evaluate any GGUF artifact (fp16/q8_0/q4_k_m) with the same llama_cpp backend and same harnes.

This gives backend parity so precision is the main variable changing across runs.

In [12]:
with BENCHMARK_PATH.open() as f:
    bench = json.load(f)

def run_humaneval_gguf(model_key="fp16", max_problems=164, timeout_sec=10):
    model_path = bench["benchmark_results"]["artifacts"][model_key]["artifact_path"]
    llm = Llama(model_path=model_path, n_ctx=2048, n_threads=8, n_gpu_layers=-1, verbose=False)

    def generate_completion_gguf(problem):
        prompt = (
            "Complete the following Python function. Return raw Python code only with correct "
            "newlines and indentation. Do not use markdown fences or explanations.\n\n"
            + problem["prompt"]
        )
        out = llm(prompt, max_tokens=512, temperature=0.0, top_p=1.0)
        text = out["choices"][0]["text"]
        return text.replace("\r\n", "\n").replace("\r", "\n").replace("Ġ", " ").replace("Ċ", "\n").rstrip()
    
    ds = load_dataset("openai/openai_humaneval", split="test")
    subset = ds.select(range(min(max_problems, len(ds))))

    results, t0 = [], time.time()
    for i, problem in enumerate(subset, start=1):
        p0 = time.time()
        generated = generate_completion_gguf(problem)
        code = clean_and_extract(generated, problem)
        full_code = code + "\n\n" + problem["test"] + f"\ncheck({problem['entry_point']})"
        result = execute_with_timeout(full_code, timeout=timeout_sec)
        results.append({
            "task_id": problem["task_id"],
            "result": result,
            "generated": generated,
            "elapsed_sec": time.time() - p0,
        })
        if i % 10 == 0 or i == len(subset):
            n_pass = sum(1 for r in results if r["result"] == "passed")
            print(f"[{i:3d}/{len(subset)}] running pass rate: {100*n_pass/i:.2f}%")

    n_total = len(results)
    n_passed = sum(1 for r in results if r["result"] == "passed")
    pass1 = 100.0 * n_passed / n_total

    out = {
        "timestamp_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "model_key": model_key,
        "model_path": model_path,
        "n_total": n_total,
        "n_passed": n_passed,
        "candidate_pass_at_1_percent": pass1,
        "runtime_sec_total": time.time() - t0,
        "results": results,
    }
    run_ts = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_path = RESULTS_DIR / f"07_{model_key}_humaneval_{run_ts}.json"
    with out_path.open("w") as f:
        json.dump(out, f, indent=2)

    print(f"\nDone. {model_key} pass@1 = {pass1:.6f}")
    print(f"saved: {out_path}")
    return out

In [13]:
with BENCHMARK_PATH.open() as f:                                                                                         
    bench = json.load(f)                                                                                                 

def load_model(model):
    # first, remove existing model(s) in memory
    for name in ["model", "tokenizer", "llm", "llm_fp16", "llm_q8", "llm_q4"]:                                               
        if name in globals():                                                                                                
            del globals()[name]                                                                                              
                                                                                                                            
    gc.collect()                                                                                                             
                                                                                                                            
    try:                                                                                                                     
        import torch                                                                                                         
        if hasattr(torch, "mps") and torch.backends.mps.is_available():                                                      
            torch.mps.empty_cache()                                                                                          
    except Exception:                                                                                                        
        pass                                                                                                                 
                                                                                                                            
    print("Cleanup done.")   

    # Then, load the new model
    model_path = bench["benchmark_results"]["artifacts"][model]["artifact_path"]

    llm = Llama(
        model_path=model_path,
        n_ctx=2048,
        n_threads=8,
        n_gpu_layers=-1,
        verbose=False,
    )

    print(f"Loaded {model} model: {model_path}")

In [14]:
load_model("q4_k_m")

Cleanup done.

llama_context: setting new yarn_attn_factor = 1.0000 (mscale == 0.7, mscale_all_dim = 0.7)
llama_context: n_ctx_seq (2048) < n_ctx_train (163840) -- the full capacity of the model will not be utilized

Loaded q4_k_m model: /Users/jarrett/dev/quantization-study/exports/DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf

In [15]:
# Test humanevals on q4 gguf
run_humaneval_gguf("q4_k_m", max_problems=164)

llama_context: setting new yarn_attn_factor = 1.0000 (mscale == 0.7, mscale_all_dim = 0.7)
llama_context: n_ctx_seq (2048) < n_ctx_train (163840) -- the full capacity of the model will not be utilized

[ 10/164] running pass rate: 100.00%
[ 20/164] running pass rate: 100.00%
[ 30/164] running pass rate: 93.33%
[ 40/164] running pass rate: 90.00%
[ 50/164] running pass rate: 90.00%
[ 60/164] running pass rate: 90.00%
[ 70/164] running pass rate: 87.14%
[ 80/164] running pass rate: 85.00%
[ 90/164] running pass rate: 83.33%
[100/164] running pass rate: 82.00%
[110/164] running pass rate: 80.91%
[120/164] running pass rate: 81.67%
[130/164] running pass rate: 78.46%
[140/164] running pass rate: 75.00%
[150/164] running pass rate: 74.67%
[160/164] running pass rate: 75.62%
[164/164] running pass rate: 75.00%

Done. q4_k_m pass@1 = 75.000000
saved: /Users/jarrett/dev/quantization-study/results/07_q4_k_m_humaneval_20260511T130907Z.json

{'timestamp_utc': '2026-05-11T13:09:07.463510+00:00',
 'model_key': 'q4_k_m',
 'model_path': '/Users/jarrett/dev/quantization-study/exports/DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf',
 'n_total': 164,
 'n_passed': 123,
 'candidate_pass_at_1_percent': 75.0,
 'runtime_sec_total': 202.24286699295044,
 'results': [{'task_id': 'HumanEval/0',
   'result': 'passed',
   'generated': '    numbers.sort()\n    for i in range(len(numbers) - 1):\n        if numbers[i + 1] - numbers[i] < threshold:\n            return True\n    return False',
   'elapsed_sec': 1.0794990062713623},
  {'task_id': 'HumanEval/1',
   'result': 'passed',
   'generated': "    result = []\n    stack = []\n    current_group = []\n\n    for char in paren_string:\n        if char == ' ':\n            continue\n        if char == '(':\n            stack.append(char)\n            current_group.append(char)\n        elif char == ')':\n            stack.pop()\n            current_group.append(char)\n            if not stack:\n                result.append(''.join(current_group))\n                current_group = []\n\n    return result",
   'elapsed_sec': 1.0744309425354004},
  {'task_id': 'HumanEval/2',
   'result': 'passed',
   'generated': '    integer_part = int(number)\n    decimal_part = number - integer_part\n    return decimal_part',
   'elapsed_sec': 4.491905212402344},
  {'task_id': 'HumanEval/3',
   'result': 'passed',
   'generated': '    balance = 0\n    for operation in operations:\n        balance += operation\n        if balance < 0:\n            return True\n    return False',
   'elapsed_sec': 0.43105578422546387},
  {'task_id': 'HumanEval/4',
   'result': 'passed',
   'generated': '    if not numbers:\n        return 0.0\n    mean = sum(numbers) / len(numbers)\n    deviations = [abs(x - mean) for x in numbers]\n    mad = sum(deviations) / len(deviations)\n    return mad\n\n# Example usage:\n# print(mean_absolute_deviation([1.0, 2.0, 3.0, 4.0]))  # Output: 1.0',
   'elapsed_sec': 0.9866929054260254},
  {'task_id': 'HumanEval/5',
   'result': 'passed',
   'generated': '    result = []\n    for i in range(len(numbers)):\n        result.append(numbers[i])\n        if i < len(numbers) - 1:\n            result.append(delimeter)\n    return result',
   'elapsed_sec': 0.5571408271789551},
  {'task_id': 'HumanEval/6',
   'result': 'passed',
   'generated': "    result = []\n    for group in paren_string.split():\n        max_depth = 0\n        current_depth = 0\n        for char in group:\n            if char == '(':\n                current_depth += 1\n                max_depth = max(max_depth, current_depth)\n            elif char == ')':\n                current_depth -= 1\n        result.append(max_depth)\n    return result",
   'elapsed_sec': 0.9395020008087158},
  {'task_id': 'HumanEval/7',
   'result': 'passed',
   'generated': '    return [s for s in strings if substring in s]',
   'elapsed_sec': 0.266765832901001},
  {'task_id': 'HumanEval/8',
   'result': 'passed',
   'generated': '    total_sum = 0\n    total_product = 1\n    for num in numbers:\n        total_sum += num\n        total_product *= num\n    return total_sum, total_product',
   'elapsed_sec': 0.5297949314117432},
  {'task_id': 'HumanEval/9',
   'result': 'passed',
   'generated': "    rolling_max_list = []\n    current_max = float('-inf')\n    for number in numbers:\n        current_max = max(current_max, number)\n        rolling_max_list.append(current_max)\n    return rolling_max_list",
   'elapsed_sec': 0.6451210975646973},
  {'task_id': 'HumanEval/10',
   'result': 'passed',
   'generated': '    if is_palindrome(string):\n        return string\n    for i in range(len(string)):\n        suffix = string[i:]\n        if is_palindrome(suffix):\n            prefix = string[:i]\n            return string + prefix[::-1]\n    return string + string[::-1]\n\n\ndef make_palindrome_efficient(string: str) -> str:\n    """ Find the shortest palindrome that begins with a supplied string.\n    Algorithm idea is simple:\n    - Find the longest postfix of supplied string that is a palindrome.\n    - Append to the end of the string reverse of a string prefix that comes before the palindromic suffix.\n    """\n    i = 0\n    while i < len(string) and string[i] == string[len(string) - 1 - i]:\n        i += 1\n    return string + string[:i][::-1]\n\n\ndef make_palindrome_with_prefix_table(string: str) -> str:\n    """ Find the shortest palindrome that begins with a supplied string.\n    Algorithm idea is simple:\n    - Find the longest postfix of supplied string that is a palindrome.\n    - Append to the end of the string reverse of a string prefix that comes before the palindromic suffix.\n    """\n    if is_palindrome(string):\n        return string\n    prefix_table = [0] * len(string)\n    j = 0\n    for i in range(1, len(string)):\n        while j > 0 and string[i] != string[j]:\n            j = prefix_table[j - 1]\n        if string[i] == string[j]:\n            j += 1\n        prefix_table[i] = j\n    return string + string[:len(string) - prefix_table[-1]][::-1]',
   'elapsed_sec': 4.493772029876709},
  {'task_id': 'HumanEval/11',
   'result': 'passed',
   'generated': "    result = []\n    for i in range(len(a)):\n        xor_result = str(int(a[i]) ^ int(b[i]))\n        result.append(xor_result)\n    return ''.join(result)\n\n# Example usage:\n# print(string_xor('010', '110'))  # Output should be '100'",
   'elapsed_sec': 0.8684742450714111},
  {'task_id': 'HumanEval/12',
   'result': 'passed',
   'generated': '    if not strings:\n        return None\n    longest_string = strings[0]\n    for string in strings:\n        if len(string) > len(longest_string):\n            longest_string = string\n    return longest_string',
   'elapsed_sec': 0.5921330451965332},
  {'task_id': 'HumanEval/13',
   'result': 'passed',
   'generated': '    while b:\n        a, b = b, a % b\n    return a',
   'elapsed_sec': 0.3150370121002197},
  {'task_id': 'HumanEval/14',
   'result': 'passed',
   'generated': '    return [string[:i] for i in range(1, len(string) + 1)]',
   'elapsed_sec': 0.4584782123565674},
  {'task_id': 'HumanEval/15',
   'result': 'passed',
   'generated': '    return " ".join(str(i) for i in range(n + 1))',
   'elapsed_sec': 0.3142578601837158},
  {'task_id': 'HumanEval/16',
   'result': 'passed',
   'generated': '    return len(set(string.lower()))',
   'elapsed_sec': 0.2433152198791504},
  {'task_id': 'HumanEval/17',
   'result': 'passed',
   'generated': '    pass\n\n\n# Solution\nfrom typing import List\n\n\ndef parse_music(music_string: str) -> List[int]:\n    """ Input to this function is a string representing musical notes in a special ASCII format.\n    Your task is to parse this string and return list of integers corresponding to how many beats does each\n    not last.\n\n    Here is a legend:\n    \'o\' - whole note, lasts four beats\n    \'o|\' - half note, lasts two beats\n    \'.|\' - quater note, lasts one beat\n\n    >>> parse_music(\'o o| .| o| o| .| .| .| .| o o\')\n    [4, 2, 1, 2, 2, 1, 1, 1, 1, 4, 4]\n    """\n    notes = music_string.split()\n    beats = []\n    for note in notes:\n        if note == \'o\':\n            beats.append(4)\n        elif note == \'o|\':\n            beats.append(2)\n        elif note == \'.|\':\n            beats.append(1)\n    return beats',
   'elapsed_sec': 2.398772954940796},
  {'task_id': 'HumanEval/18',
   'result': 'passed',
   'generated': '    count = 0\n    start = 0\n    while True:\n        start = string.find(substring, start) + 1\n        if start > 0:\n            count += 1\n        else:\n            break\n    return count\n\n# Example usage:\n# print(how_many_times("hello world", "o"))\n# This should output 2, as "o" appears twice in "hello world".',
   'elapsed_sec': 0.9137539863586426},
  {'task_id': 'HumanEval/19',
   'result': 'passed',
   'generated': "    num_dict = {'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 'six': 6, 'seven': 7, 'eight': 8, 'nine': 9}\n    words = numbers.split()\n    sorted_words = sorted(words, key=lambda word: num_dict[word])\n    return ' '.join(sorted_words)",
   'elapsed_sec': 0.9947676658630371},
  {'task_id': 'HumanEval/20',
   'result': 'failed',
   'generated': "    min_diff = float('inf')\n    closest_pair = (0.0, 0.0)\n\n    for i in range(len(numbers)):\n        for j in range(i + 1, len(numbers)):\n            diff = abs(numbers[i] - numbers[j])\n            if diff < min_diff:\n                min_diff = diff\n                closest_pair = (numbers[i], numbers[j])\n\n    return closest_pair",
   'elapsed_sec': 1.054198980331421},
  {'task_id': 'HumanEval/21',
   'result': 'passed',
   'generated': '    min_val = min(numbers)\n    max_val = max(numbers)\n    return [(x - min_val) / (max_val - min_val) for x in numbers]\n\n# Example usage:\n# print(rescale_to_unit([1.0, 2.0, 3.0, 4.0, 5.0]))\n# Output: [0.0, 0.25, 0.5, 0.75, 1.0]',
   'elapsed_sec': 1.0882461071014404},
  {'task_id': 'HumanEval/22',
   'result': 'passed',
   'generated': '    return [value for value in values if isinstance(value, int)]',
   'elapsed_sec': 0.28932690620422363},
  {'task_id': 'HumanEval/23',
   'result': 'passed',
   'generated': '    count = 0\n    for char in string:\n        count += 1\n    return count',
   'elapsed_sec': 4.454026937484741},
  {'task_id': 'HumanEval/24',
   'result': 'passed',
   'generated': '    for i in range(n // 2, 0, -1):\n        if n % i == 0:\n            return i\n    return 1\n\n# Example usage:\n# print(largest_divisor(15))  # Output: 5\n# print(largest_divisor(29))  # Output: 1\n# print(largest_divisor(100)) # Output: 50',
   'elapsed_sec': 0.8978409767150879},
  {'task_id': 'HumanEval/25',
   'result': 'passed',
   'generated': '    factors = []\n    # Start with the smallest prime factor\n    divisor = 2\n    while divisor <= n:\n        while n % divisor == 0:\n            factors.append(divisor)\n            n //= divisor\n        divisor += 1\n    return factors',
   'elapsed_sec': 0.6589090824127197},
  {'task_id': 'HumanEval/26',
   'result': 'failed',
   'generated': '    seen = set()\n    result = []\n    for num in numbers:\n        if num not in seen:\n            seen.add(num)\n            result.append(num)\n    return result',
   'elapsed_sec': 0.5221679210662842},
  {'task_id': 'HumanEval/27',
   'result': 'passed',
   'generated': "    result = []\n    for char in string:\n        if char.islower():\n            result.append(char.upper())\n        elif char.isupper():\n            result.append(char.lower())\n        else:\n            result.append(char)\n    return ''.join(result)",
   'elapsed_sec': 0.679858922958374},
  {'task_id': 'HumanEval/28',
   'result': 'passed',
   'generated': '    result = \'\'\n    for s in strings:\n        result += s\n    return result\n\n# Example usage:\n# print(concatenate([\'a\', \'b\', \'c\']))\n# print(concatenate([]))\n\n# Test cases:\n# print(concatenate([\'a\', \'b\', \'c\']))  # Output should be \'abc\'\n# print(concatenate([\'hello\', \'world\']))  # Output should be \'helloworld\'\n# print(concatenate([\'Python\', \'3\']))  # Output should be \'Python3\'\n# print(concatenate([]))  # Output should be \'\'\n# print(concatenate([\'single\']))  # Output should be \'single\'\n\nfrom typing import List\n\n\ndef concatenate(strings: List[str]) -> str:\n    """ Concatenate list of strings into a single string\n    \n    >>> concatenate([])\n    \'\'\n    >>> concatenate([\'a\', \'b\', \'c\'])\n    \'abc\'\n    """\n    result = \'\'\n    for s in strings:\n        result += s\n    return result',
   'elapsed_sec': 2.175840139389038},
  {'task_id': 'HumanEval/29',
   'result': 'passed',
   'generated': '    result = []\n    for string in strings:\n        if string.startswith(prefix):\n            result.append(string)\n    return result',
   'elapsed_sec': 0.41491079330444336},
  {'task_id': 'HumanEval/30',
   'result': 'passed',
   'generated': '    pass\n\n\n\nSolution:\n\n```python\ndef get_positive(l: list):\n    """Return only positive numbers in the list.\n    \n    >>> get_positive([-1, 2, -4, 5, 6])\n    [2, 5, 6]\n    >>> get_positive([5, 3, -5, 2, -3, 3, 9, 0, 123, 1, -10])\n    [5, 3, 2, 3, 9, 123, 1]\n    """\n    return [num for num in l if num > 0]\n```',
   'elapsed_sec': 1.4124720096588135},
  {'task_id': 'HumanEval/31',
   'result': 'passed',
   'generated': '    if n <= 1:\n        return False\n    if n <= 3:\n        return True\n    if n % 2 == 0 or n % 3 == 0:\n        return False\n    i = 5\n    while i * i <= n:\n        if n % i == 0 or n % (i + 2) == 0:\n            return False\n        i += 6\n    return True',
   'elapsed_sec': 0.9212398529052734},
  {'task_id': 'HumanEval/32',
   'result': 'failed',
   'generated': '    assert len(xs) % 2 == 0 and max(xs) != 0, "xs must have even number of coefficients and largest non-zero coefficient"\n    low, high = -100, 100\n    while high - low > 1e-9:\n        mid = (low + high) / 2\n        if poly(xs, mid) > 0:\n            high = mid\n        else:\n            low = mid\n    return (low + high) / 2',
   'elapsed_sec': 1.2089641094207764},
  {'task_id': 'HumanEval/33',
   'result': 'passed',
   'generated': '    pass\n\n\n\n# Solution:\n\ndef sort_third(l: list):\n    """This function takes a list l and returns a list l\' such that\n    l\' is identical to l in the indicies that are not divisible by three, while its values at the indicies that are divisible by three are equal\n    to the values of the corresponding indicies of l, but sorted.\n    >>> sort_third([1, 2, 3])\n    [1, 2, 3]\n    >>> sort_third([5, 6, 3, 4, 8, 9, 2])\n    [2, 6, 3, 4, 8, 9, 5]\n    """\n    third_elements = [l[i] for i in range(len(l)) if i % 3 == 0]\n    third_elements.sort()\n    result = l[:]\n    for i, val in zip(range(0, len(l), 3), third_elements):\n        result[i] = val\n    return result',
   'elapsed_sec': 2.215230941772461},
  {'task_id': 'HumanEval/34',
   'result': 'passed',
   'generated': '    pass\n\n\n\n# Solution:\n\ndef unique(l: list):\n    """Return sorted unique elements in a list\n    >>> unique([5, 3, 5, 2, 3, 3, 9, 0, 123])\n    [0, 2, 3, 5, 9, 123]\n    """\n    return sorted(set(l))',
   'elapsed_sec': 0.891211986541748},
  {'task_id': 'HumanEval/35',
   'result': 'passed',
   'generated': '    pass\n\n\n# Solution:\n\ndef max_element(l: list):\n    """Return maximum element in the list.\n    \n    >>> max_element([1, 2, 3])\n    3\n    >>> max_element([5, 3, -5, 2, -3, 3, 9, 0, 123, 1, -10])\n    123\n    """\n    return max(l)',
   'elapsed_sec': 0.973689079284668},
  {'task_id': 'HumanEval/36',
   'result': 'failed',
   'generated': "    count = 0\n    for i in range(1, n):\n        if i % 11 == 0 or i % 13 == 0:\n            if '7' in str(i):\n                count += 1\n    return count",
   'elapsed_sec': 0.6134350299835205},
  {'task_id': 'HumanEval/37',
   'result': 'passed',
   'generated': '    evens = sorted([l[i] for i in range(len(l)) if i % 2 == 0])\n    result = l[:]\n    even_index = 0\n    for i in range(len(l)):\n        if i % 2 == 0:\n            result[i] = evens[even_index]\n            even_index += 1\n    return result',
   'elapsed_sec': 0.878485918045044},
  {'task_id': 'HumanEval/38',
   'result': 'passed',
   'generated': '    # split string to groups. Each of length 3.\n    groups = [s[(3 * i):min((3 * i + 3), len(s))] for i in range((len(s) + 2) // 3)]\n    # cycle elements in each group in reverse. Unless group has fewer elements than 3.\n    groups = [(group[-1] + group[:-1]) if len(group) == 3 else group for group in groups]\n    return "".join(groups)',
   'elapsed_sec': 1.1191229820251465},
  {'task_id': 'HumanEval/39',
   'result': 'passed',
   'generated': '    def is_prime(num):\n        if num <= 1:\n            return False\n        if num <= 3:\n            return True\n        if num % 2 == 0 or num % 3 == 0:\n            return False\n        i = 5\n        while i * i <= num:\n            if num % i == 0 or num % (i + 2) == 0:\n                return False\n            i += 6\n        return True\n\n    def fib(n):\n        a, b = 0, 1\n        for _ in range(n - 1):\n            a, b = b, a + b\n        return a\n\n    count = 0\n    i = 0\n    while True:\n        fib_num = fib(i)\n        if is_prime(fib_num):\n            count += 1\n            if count == n:\n                return fib_num\n        i += 1\n\n    return None',
   'elapsed_sec': 1.9685161113739014},
  {'task_id': 'HumanEval/40',
   'result': 'passed',
   'generated': '    l.sort()\n    for i in range(len(l) - 2):\n        left, right = i + 1, len(l) - 1\n        while left < right:\n            current_sum = l[i] + l[left] + l[right]\n            if current_sum == 0:\n                return True\n            elif current_sum < 0:\n                left += 1\n            else:\n                right -= 1\n    return False',
   'elapsed_sec': 1.225701093673706},
  {'task_id': 'HumanEval/41',
   'result': 'failed',
   'generated': '    return n * (n - 1) // 2\n\n# Example usage:\n# print(car_race_collision(3))  # Should output 3\n# print(car_race_collision(4))  # Should output 6\n# print(car_race_collision(5))  # Should output 10',
   'elapsed_sec': 0.7711012363433838},
  {'task_id': 'HumanEval/42',
   'result': 'passed',
   'generated': '    return [x + 1 for x in l]',
   'elapsed_sec': 0.26401805877685547},
  {'task_id': 'HumanEval/43',
   'result': 'passed',
   'generated': '    seen = set()\n    for num in l:\n        if -num in seen:\n            return True\n        seen.add(num)\n    return False',
   'elapsed_sec': 0.4760289192199707},
  {'task_id': 'HumanEval/44',
   'result': 'passed',
   'generated': "    if x == 0:\n        return '0'\n    digits = '0123456789'\n    result = ''\n    while x > 0:\n        result = digits[x % base] + result\n        x //= base\n    return result",
   'elapsed_sec': 0.6728649139404297},
  {'task_id': 'HumanEval/45',
   'result': 'passed',
   'generated': '    return (a * h) / 2',
   'elapsed_sec': 0.23238611221313477},
  {'task_id': 'HumanEval/46',
   'result': 'passed',
   'generated': '    if n == 0:\n        return 0\n    elif n == 1:\n        return 0\n    elif n == 2:\n        return 2\n    elif n == 3:\n        return 0\n    else:\n        a, b, c, d = 0, 0, 2, 0\n        for i in range(4, n + 1):\n            e = a + b + c + d\n            a, b, c, d = b, c, d, e\n        return d',
   'elapsed_sec': 1.2134509086608887},
  {'task_id': 'HumanEval/47',
   'result': 'passed',
   'generated': '    pass\n\n\n\nSolution:\n\n```python\ndef median(l: list):\n    """Return median of elements in the list l.\n    \n    >>> median([3, 1, 2, 4, 5])\n    3\n    >>> median([-10, 4, 6, 1000, 10, 20])\n    15.0\n    """\n    sorted_list = sorted(l)\n    n = len(sorted_list)\n    if n % 2 == 1:\n        return sorted_list[n // 2]\n    else:\n        return (sorted_list[n // 2 - 1] + sorted_list[n // 2]) / 2\n```',
   'elapsed_sec': 1.5128822326660156},
  {'task_id': 'HumanEval/48',
   'result': 'passed',
   'generated': '    pass\n\n\n# Solution:\n\ndef is_palindrome(text: str):\n    """\n    Checks if given string is a palindrome\n    \n    >>> is_palindrome(\'\')\n    True\n    >>> is_palindrome(\'aba\')\n    True\n    >>> is_palindrome(\'aaaaa\')\n    True\n    >>> is_palindrome(\'zbcd\')\n    False\n    """\n    cleaned_text = \'\'.join(char.lower() for char in text if char.isalnum())\n    return cleaned_text == cleaned_text[::-1]',
   'elapsed_sec': 1.2195489406585693},
  {'task_id': 'HumanEval/49',
   'result': 'passed',
   'generated': '    return pow(2, n, p)',
   'elapsed_sec': 0.26097893714904785},
  {'task_id': 'HumanEval/50',
   'result': 'passed',

In [16]:
load_model("q8_0")

Cleanup done.

llama_context: setting new yarn_attn_factor = 1.0000 (mscale == 0.7, mscale_all_dim = 0.7)
llama_context: n_ctx_seq (2048) < n_ctx_train (163840) -- the full capacity of the model will not be utilized

Loaded q8_0 model: /Users/jarrett/dev/quantization-study/exports/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf

In [17]:
# Test humanevals on q8 gguf
run_humaneval_gguf("q8_0", max_problems=164)

llama_context: setting new yarn_attn_factor = 1.0000 (mscale == 0.7, mscale_all_dim = 0.7)
llama_context: n_ctx_seq (2048) < n_ctx_train (163840) -- the full capacity of the model will not be utilized

[ 10/164] running pass rate: 100.00%
[ 20/164] running pass rate: 100.00%
[ 30/164] running pass rate: 96.67%
[ 40/164] running pass rate: 90.00%
[ 50/164] running pass rate: 88.00%
[ 60/164] running pass rate: 86.67%
[ 70/164] running pass rate: 84.29%
[ 80/164] running pass rate: 83.75%
[ 90/164] running pass rate: 82.22%
[100/164] running pass rate: 82.00%
[110/164] running pass rate: 78.18%
[120/164] running pass rate: 78.33%
[130/164] running pass rate: 75.38%
[140/164] running pass rate: 72.14%
[150/164] running pass rate: 72.00%
[160/164] running pass rate: 72.50%
[164/164] running pass rate: 71.95%

Done. q8_0 pass@1 = 71.951220
saved: /Users/jarrett/dev/quantization-study/results/07_q8_0_humaneval_20260511T131758Z.json

{'timestamp_utc': '2026-05-11T13:17:58.904263+00:00',
 'model_key': 'q8_0',
 'model_path': '/Users/jarrett/dev/quantization-study/exports/DeepSeek-Coder-V2-Lite-Instruct-Q8_0.gguf',
 'n_total': 164,
 'n_passed': 118,
 'candidate_pass_at_1_percent': 71.95121951219512,
 'runtime_sec_total': 214.18932461738586,
 'results': [{'task_id': 'HumanEval/0',
   'result': 'passed',
   'generated': '    for i in range(len(numbers)):\n        for j in range(i + 1, len(numbers)):\n            if abs(numbers[i] - numbers[j]) < threshold:\n                return True\n    return False',
   'elapsed_sec': 0.7529768943786621},
  {'task_id': 'HumanEval/1',
   'result': 'passed',
   'generated': "    result = []\n    stack = []\n    current_group = []\n\n    for char in paren_string:\n        if char == ' ':\n            continue\n        if char == '(':\n            stack.append(char)\n            current_group.append(char)\n        elif char == ')':\n            stack.pop()\n            current_group.append(char)\n            if not stack:\n                result.append(''.join(current_group))\n                current_group = []\n\n    return result",
   'elapsed_sec': 1.2432188987731934},
  {'task_id': 'HumanEval/2',
   'result': 'passed',
   'generated': '    return number - int(number)',
   'elapsed_sec': 0.24199295043945312},
  {'task_id': 'HumanEval/3',
   'result': 'passed',
   'generated': '    balance = 0\n    for operation in operations:\n        balance += operation\n        if balance < 0:\n            return True\n    return False',
   'elapsed_sec': 0.47777700424194336},
  {'task_id': 'HumanEval/4',
   'result': 'passed',
   'generated': '    if not numbers:\n        return 0.0\n    mean = sum(numbers) / len(numbers)\n    deviations = [abs(x - mean) for x in numbers]\n    mad = sum(deviations) / len(numbers)\n    return mad',
   'elapsed_sec': 0.7113199234008789},
  {'task_id': 'HumanEval/5',
   'result': 'passed',
   'generated': '    result = []\n    for i in range(len(numbers)):\n        result.append(numbers[i])\n        if i < len(numbers) - 1:\n            result.append(delimeter)\n    return result',
   'elapsed_sec': 0.6321158409118652},
  {'task_id': 'HumanEval/6',
   'result': 'passed',
   'generated': "    result = []\n    for group in paren_string.split():\n        max_depth = 0\n        depth = 0\n        for char in group:\n            if char == '(':\n                depth += 1\n                max_depth = max(max_depth, depth)\n            elif char == ')':\n                depth -= 1\n        result.append(max_depth)\n    return result",
   'elapsed_sec': 1.0057110786437988},
  {'task_id': 'HumanEval/7',
   'result': 'passed',
   'generated': '    return [s for s in strings if substring in s]',
   'elapsed_sec': 0.28366518020629883},
  {'task_id': 'HumanEval/8',
   'result': 'passed',
   'generated': '    sum_of_numbers = 0\n    product_of_numbers = 1\n    for number in numbers:\n        sum_of_numbers += number\n        product_of_numbers *= number\n    return sum_of_numbers, product_of_numbers',
   'elapsed_sec': 0.7059030532836914},
  {'task_id': 'HumanEval/9',
   'result': 'passed',
   'generated': "    if not numbers:\n        return []\n\n    rolling_max_list = []\n    current_max = float('-inf')\n\n    for number in numbers:\n        current_max = max(current_max, number)\n        rolling_max_list.append(current_max)\n\n    return rolling_max_list",
   'elapsed_sec': 0.8452870845794678},
  {'task_id': 'HumanEval/10',
   'result': 'passed',
   'generated': '    if is_palindrome(string):\n        return string\n    for i in range(len(string)):\n        substring = string[i:]\n        if is_palindrome(substring):\n            return string + string[:i][::-1]\n    return string + string[::-1]\n\n\ndef main():\n    print(make_palindrome(\'\'))\n    print(make_palindrome(\'cat\'))\n    print(make_palindrome(\'cata\'))\n\n\nif __name__ == "__main__":\n    main()',
   'elapsed_sec': 1.5090711116790771},
  {'task_id': 'HumanEval/11',
   'result': 'passed',
   'generated': "    result = []\n    for i in range(len(a)):\n        if a[i] == b[i]:\n            result.append('0')\n        else:\n            result.append('1')\n    return ''.join(result)",
   'elapsed_sec': 0.6764018535614014},
  {'task_id': 'HumanEval/12',
   'result': 'passed',
   'generated': '    if not strings:\n        return None\n    longest_string = strings[0]\n    for string in strings:\n        if len(string) > len(longest_string):\n            longest_string = string\n    return longest_string',
   'elapsed_sec': 0.6636381149291992},
  {'task_id': 'HumanEval/13',
   'result': 'passed',
   'generated': '    while b:\n        a, b = b, a % b\n    return a',
   'elapsed_sec': 0.3314981460571289},
  {'task_id': 'HumanEval/14',
   'result': 'passed',
   'generated': '    return [string[:i] for i in range(1, len(string) + 1)]',
   'elapsed_sec': 0.36086225509643555},
  {'task_id': 'HumanEval/15',
   'result': 'passed',
   'generated': "    return ' '.join(str(i) for i in range(n + 1))",
   'elapsed_sec': 0.3430190086364746},
  {'task_id': 'HumanEval/16',
   'result': 'passed',
   'generated': '    return len(set(string.lower()))',
   'elapsed_sec': 0.2507028579711914},
  {'task_id': 'HumanEval/17',
   'result': 'passed',
   'generated': '    pass\n\n# Solution:\n\nfrom typing import List\n\n\ndef parse_music(music_string: str) -> List[int]:\n    """ Input to this function is a string representing musical notes in a special ASCII format.\n    Your task is to parse this string and return list of integers corresponding to how many beats does each\n    not last.\n\n    Here is a legend:\n    \'o\' - whole note, lasts four beats\n    \'o|\' - half note, lasts two beats\n    \'.|\' - quater note, lasts one beat\n\n    >>> parse_music(\'o o| .| o| o| .| .| .| .| o o\')\n    [4, 2, 1, 2, 2, 1, 1, 1, 1, 4, 4]\n    """\n    notes = music_string.split()\n    beats = []\n    for note in notes:\n        if note == \'o\':\n            beats.append(4)\n        elif note == \'o|\':\n            beats.append(2)\n        elif note == \'.|\':\n            beats.append(1)\n    return beats',
   'elapsed_sec': 2.7881479263305664},
  {'task_id': 'HumanEval/18',
   'result': 'passed',
   'generated': '    count = 0\n    start = 0\n    while start < len(string):\n        pos = string.find(substring, start)\n        if pos == -1:\n            break\n        count += 1\n        start = pos + 1\n    return count',
   'elapsed_sec': 0.7270467281341553},
  {'task_id': 'HumanEval/19',
   'result': 'passed',
   'generated': "    num_dict = {'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 'six': 6, 'seven': 7, 'eight': 8, 'nine': 9}\n    num_list = numbers.split()\n    num_list.sort(key=lambda x: num_dict[x])\n    return ' '.join(num_list)",
   'elapsed_sec': 1.1381309032440186},
  {'task_id': 'HumanEval/20',
   'result': 'passed',
   'generated': "    min_diff = float('inf')\n    closest_pair = (0.0, 0.0)\n\n    for i in range(len(numbers)):\n        for j in range(i + 1, len(numbers)):\n            diff = abs(numbers[i] - numbers[j])\n            if diff < min_diff:\n                min_diff = diff\n                closest_pair = (min(numbers[i], numbers[j]), max(numbers[i], numbers[j]))\n\n    return closest_pair",
   'elapsed_sec': 1.323683261871338},
  {'task_id': 'HumanEval/21',
   'result': 'passed',
   'generated': '    min_val = min(numbers)\n    max_val = max(numbers)\n    return [(x - min_val) / (max_val - min_val) for x in numbers]',
   'elapsed_sec': 0.5846290588378906},
  {'task_id': 'HumanEval/22',
   'result': 'passed',
   'generated': '    return [value for value in values if isinstance(value, int)]',
   'elapsed_sec': 0.30826306343078613},
  {'task_id': 'HumanEval/23',
   'result': 'passed',
   'generated': '    count = 0\n    for char in string:\n        count += 1\n    return count\n\n\n\n```python\ndef strlen(string: str) -> int:\n    """ Return length of given string\n    >>> strlen(\'\')\n    0\n    >>> strlen(\'abc\')\n    3\n    """\n    count = 0\n    for char in string:\n        count += 1\n    return count\n```',
   'elapsed_sec': 0.9976341724395752},
  {'task_id': 'HumanEval/24',
   'result': 'passed',
   'generated': '    for i in range(n // 2, 0, -1):\n        if n % i == 0:\n            return i\n    return 1',
   'elapsed_sec': 0.4795510768890381},
  {'task_id': 'HumanEval/25',
   'result': 'passed',
   'generated': '    i = 2\n    factors = []\n    while i * i <= n:\n        if n % i:\n            i += 1\n        else:\n            n //= i\n            factors.append(i)\n    if n > 1:\n        factors.append(n)\n    return factors',
   'elapsed_sec': 0.8240749835968018},
  {'task_id': 'HumanEval/26',
   'result': 'failed',
   'generated': '    seen = {}\n    result = []\n    for number in numbers:\n        if number not in seen:\n            seen[number] = 1\n            result.append(number)\n        elif seen[number] == 1:\n            seen[number] += 1\n    return result\n\n# The function above has a bug. Fix it.\n\nCorrected function:\n\n```python\nfrom typing import List\n\n\ndef remove_duplicates(numbers: List[int]) -> List[int]:\n    """ From a list of integers, remove all elements that occur more than once.\n    Keep order of elements left the same as in the input.\n    >>> remove_duplicates([1, 2, 3, 2, 4])\n    [1, 3, 4]\n    """\n    seen = {}\n    result = []\n    for number in numbers:\n        if number not in seen:\n            seen[number] = 1\n            result.append(number)\n        else:\n            if seen[number] == 1:\n                seen[number] += 1\n    return result\n```',
   'elapsed_sec': 2.5729997158050537},
  {'task_id': 'HumanEval/27',
   'result': 'passed',
   'generated': '    result = ""\n    for char in string:\n        if char.islower():\n            result += char.upper()\n        elif char.isupper():\n            result += char.lower()\n        else:\n            result += char\n    return result',
   'elapsed_sec': 0.6651849746704102},
  {'task_id': 'HumanEval/28',
   'result': 'passed',
   'generated': "    result = ''\n    for s in strings:\n        result += s\n    return result",
   'elapsed_sec': 0.3444840908050537},
  {'task_id': 'HumanEval/29',
   'result': 'passed',
   'generated': '    return [s for s in strings if s.startswith(prefix)]',
   'elapsed_sec': 0.3062872886657715},
  {'task_id': 'HumanEval/30',
   'result': 'passed',
   'generated': '    return [x for x in l if x > 0]',
   'elapsed_sec': 0.30288100242614746},
  {'task_id': 'HumanEval/31',
   'result': 'passed',
   'generated': '    if n <= 1:\n        return False\n    if n <= 3:\n        return True\n    if n % 2 == 0 or n % 3 == 0:\n        return False\n    i = 5\n    while i * i <= n:\n        if n % i == 0 or n % (i + 2) == 0:\n            return False\n        i += 6\n    return True',
   'elapsed_sec': 1.0466158390045166},
  {'task_id': 'HumanEval/32',
   'result': 'failed',
   'generated': '    assert len(xs) % 2 == 0 and xs[-1] != 0, "Polynomial must have even number of coefficients and non-zero leading coefficient."\n    low = -1000\n    high = 1000\n    while high - low > 1e-7:\n        mid = (low + high) / 2\n        if poly(xs, mid) > 0:\n            high = mid\n        else:\n            low = mid\n    return (low + high) / 2',
   'elapsed_sec': 1.3985249996185303},
  {'task_id': 'HumanEval/33',
   'result': 'failed',
   'generated': '    pass\n\n\n\n```python\ndef sort_third(l: list):\n    third_elements = [l[i] for i in range(2, len(l), 3)]\n    third_elements.sort()\n    result = l[:]\n    for i, value in zip(range(2, len(l), 3), third_elements):\n        result[i] = value\n    return result\n```',
   'elapsed_sec': 1.0770928859710693},
  {'task_id': 'HumanEval/34',
   'result': 'passed',
   'generated': '    return sorted(set(l))',
   'elapsed_sec': 0.23293113708496094},
  {'task_id': 'HumanEval/35',
   'result': 'passed',
   'generated': '    pass\n\n\n\n```python\ndef max_element(l: list):\n    return max(l)\n```',
   'elapsed_sec': 0.39992499351501465},
  {'task_id': 'HumanEval/36',
   'result': 'failed',
   'generated': "    count = 0\n    for i in range(1, n):\n        if i % 11 == 0 or i % 13 == 0:\n            if '7' in str(i):\n                count += 1\n    return count",
   'elapsed_sec': 0.6925868988037109},
  {'task_id': 'HumanEval/37',
   'result': 'passed',
   'generated': '    evens = sorted([l[i] for i in range(0, len(l), 2)])\n    result = l[:]\n    even_index = 0\n    for i in range(0, len(l), 2):\n        result[i] = evens[even_index]\n        even_index += 1\n    return result',
   'elapsed_sec': 0.9162747859954834},
  {'task_id': 'HumanEval/38',
   'result': 'passed',
   'generated': '    # split string to groups. Each of length 3.\n    groups = [s[(3 * i):min((3 * i + 3), len(s))] for i in range((len(s) + 2) // 3)]\n    # cycle elements in each group back. Unless group has fewer elements than 3.\n    groups = [(group[-1] + group[:-1]) if len(group) == 3 else group for group in groups]\n    return "".join(groups)',
   'elapsed_sec': 1.2540721893310547},
  {'task_id': 'HumanEval/39',
   'result': 'passed',
   'generated': '    def is_prime(num):\n        if num <= 1:\n            return False\n        if num <= 3:\n            return True\n        if num % 2 == 0 or num % 3 == 0:\n            return False\n        i = 5\n        while i * i <= num:\n            if num % i == 0 or num % (i + 2) == 0:\n                return False\n            i += 6\n        return True\n\n    def fib(n):\n        a, b = 0, 1\n        for _ in range(n):\n            a, b = b, a + b\n        return a\n\n    count = 0\n    i = 0\n    while True:\n        fib_num = fib(i)\n        if is_prime(fib_num):\n            count += 1\n            if count == n:\n                return fib_num\n        i += 1\n\n# Example usage:\n# print(prime_fib(1))  # Output: 2\n# print(prime_fib(2))  # Output: 3\n# print(prime_fib(3))  # Output: 5\n# print(prime_fib(4))  # Output: 13\n# print(prime_fib(5))  # Output: 89',
   'elapsed_sec': 3.066132068634033},
  {'task_id': 'HumanEval/40',
   'result': 'failed',
   'generated': '    pass',
   'elapsed_sec': 5.522295951843262},
  {'task_id': 'HumanEval/41',
   'result': 'passed',
   'generated': '    return n * n\n\n# Example usage:\n# print(car_race_collision(3))  # Should output 9\n# print(car_race_collision(4))  # Should output 16\n# print(car_race_collision(5))  # Should output 25',
   'elapsed_sec': 0.8079078197479248},
  {'task_id': 'HumanEval/42',
   'result': 'passed',
   'generated': '    return [x + 1 for x in l]',
   'elapsed_sec': 0.28122901916503906},
  {'task_id': 'HumanEval/43',
   'result': 'passed',
   'generated': '    pass\n\n\n\n```python\ndef pairs_sum_to_zero(l):\n    seen = set()\n    for num in l:\n        if -num in seen:\n            return True\n        seen.add(num)\n    return False\n```',
   'elapsed_sec': 0.7406671047210693},
  {'task_id': 'HumanEval/44',
   'result': 'passed',
   'generated': "    if x == 0:\n        return '0'\n    digits = '0123456789'\n    result = ''\n    while x > 0:\n        result = digits[x % base] + result\n        x //= base\n    return result",
   'elapsed_sec': 0.760822057723999},
  {'task_id': 'HumanEval/45',
   'result': 'passed',
   'generated': '    return (a * h) / 2',
   'elapsed_sec': 0.2479097843170166},
  {'task_id': 'HumanEval/46',
   'result': 'passed',
   'generated': '    if n == 0:\n        return 0\n    elif n == 1:\n        return 0\n    elif n == 2:\n        return 2\n    elif n == 3:\n        return 0\n    else:\n        a, b, c, d = 0, 0, 2, 0\n        for i in range(4, n + 1):\n            e = a + b + c + d\n            a, b, c, d = b, c, d, e\n        return d',
   'elapsed_sec': 1.3748390674591064},
  {'task_id': 'HumanEval/47',
   'result': 'passed',
   'generated': '    sorted_list = sorted(l)\n    n = len(sorted_list)\n    if n % 2 == 1:\n        return sorted_list[n // 2]\n    else:\n        return (sorted_list[n // 2 - 1] + sorted_list[n // 2]) / 2',
   'elapsed_sec': 0.8676152229309082},
  {'task_id': 'HumanEval/48',
   'result': 'failed',
   'generated': '    pass',
   'elapsed_sec': 5.33589506149292},
  {'task_id': 'HumanEval/49',
   'result': 'passed',
   'generated': '    return pow(2, n, p)',
   'elapsed_sec': 0.2646632194519043},
  {'task_id': 'HumanEval/50',
   'result': 'passed',
   'generated': '    return "".join([chr(((ord(ch) - 5 - ord("a")) % 26) + ord("a")) for ch in s])',
   'elapsed_sec': 0.4985809326171875},
  {'task_id': 'HumanEval/51',
   'result': 'passed',
   'generated': '    vowels = "aeiouAEIOU"\n    return \'\'.join(char for char in text if char not in vowels)',
   'elapsed_sec': 0.4586050510406494},
  {'task_id': 'HumanEval/52',
   'result': 'passed',
   'generated': '    pass\n\n\n\n```python\ndef below_threshold(l, t):\n    return all(x < t for x in l)\n```',
   'elapsed_sec': 0.46743202209472656},
  {'task_id': 'HumanEval/53',
   'result': 'passed',
   'generated': '    return x + y',
   'elapsed_sec': 5.2821879386901855},
  {'task_id': 'HumanEval/54',
   'result': 'failed',
   'generated': '    return sorted(s0) == sorted(s1)',
   'elapsed_sec': 0.3172328472137451},
  {'task_id': 'HumanEval/55',
   'result': 'passed',
   'generated': '    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a',
   'elapsed_sec': 5.277277946472168},
  {'task_id': 'HumanEval/56',
   'result': 'passed',
   'generated': '    stack = []\n    for bracket in brackets:\n        if bracket == "<":\n            stack.append(bracket)\n        elif bracket == ">":\n            if not stack:\n                return False\n            stack.pop()\n    return not stack',
   'elapsed_sec': 0.6864838600158691},
  {'task_id': 'HumanEval/57',
   'result': 'failed',
   'generated': '    increasing = all(x < y for x, y in zip(l, l[1:]))\n    decreasing = all(x > y for x, y in zip(l, l[1:]))\n    return increasing or decreasing',
   'elapsed_sec': 0.6345791816711426},
  {'task_id': 'HumanEval/58',
   'result': 'passed',
   'generated': '    return sorted(set(l1) & set(l2))',
   'elapsed_sec': 0.32562732696533203},
  {'task_id': 'HumanEval/59',
   'result': 'passed',
   'generated': '    i = 2\n    while i * i <= n:\n        if n % i:\n            i += 1\n        else:\n            n //= i\n    return n',
   'elapsed_sec': 0.548424243927002},
  {'task_id': 'HumanEval/60',
   'result': 'passed',
   'generated': '    return n * (n + 1) // 2',
   'elapsed_sec': 0.3117799758911133},
  {'task_id': 'HumanEval/61',
   'result': 'passed',
   'generated': '    stack = []\n    for bracket in brackets:\n        if bracket == "(":\n            stack.append(bracket)\n        elif bracket == ")":\n            if not stack:\n                return False\n            stack.pop()\n    return not stack',
   'elapsed_sec': 0.6755337715148926},
  {'task_id': 'HumanEval/62',
   'result': 'failed',
   'generated': '    pass',
   'elapsed_sec': 5.3786938190460205},
  {'task_id': 'HumanEval/63',
   'result': 'passed',
   'generated': '    if n == 0 or n == 1:\n        return 0\n    elif n == 2:\n        return 1\n    else:\n        a, b, c = 0, 0, 1\n        for i in range(3, n + 1):\n            a, b, c = b, c, a + b + c\n        return c',
   'elapsed_sec': 0.9822320938110352},
  {'task_id': 'HumanEval/64',
   'result': 'error: SyntaxError: invalid syntax. Perhaps you forgot a comma?',

In [18]:
load_model("fp16")

Cleanup done.

llama_context: setting new yarn_attn_factor = 1.0000 (mscale == 0.7, mscale_all_dim = 0.7)
llama_context: n_ctx_seq (2048) < n_ctx_train (163840) -- the full capacity of the model will not be utilized

Loaded fp16 model: /Users/jarrett/dev/quantization-study/exports/DeepSeek-Coder-V2-Lite-Instruct-F16.gguf

In [19]:
run_humaneval_gguf("fp16", max_problems=164)

llama_context: setting new yarn_attn_factor = 1.0000 (mscale == 0.7, mscale_all_dim = 0.7)
llama_context: n_ctx_seq (2048) < n_ctx_train (163840) -- the full capacity of the model will not be utilized

[ 10/164] running pass rate: 100.00%
[ 20/164] running pass rate: 100.00%
[ 30/164] running pass rate: 96.67%
[ 40/164] running pass rate: 90.00%
[ 50/164] running pass rate: 88.00%
[ 60/164] running pass rate: 86.67%
[ 70/164] running pass rate: 82.86%
[ 80/164] running pass rate: 83.75%
[ 90/164] running pass rate: 82.22%
[100/164] running pass rate: 83.00%
[110/164] running pass rate: 80.00%
[120/164] running pass rate: 80.00%
[130/164] running pass rate: 76.92%
[140/164] running pass rate: 72.86%
[150/164] running pass rate: 72.67%
[160/164] running pass rate: 73.12%
[164/164] running pass rate: 72.56%

Done. fp16 pass@1 = 72.560976
saved: /Users/jarrett/dev/quantization-study/results/07_fp16_humaneval_20260511T132341Z.json

{'timestamp_utc': '2026-05-11T13:23:41.123848+00:00',
 'model_key': 'fp16',
 'model_path': '/Users/jarrett/dev/quantization-study/exports/DeepSeek-Coder-V2-Lite-Instruct-F16.gguf',
 'n_total': 164,
 'n_passed': 119,
 'candidate_pass_at_1_percent': 72.5609756097561,
 'runtime_sec_total': 322.9743947982788,
 'results': [{'task_id': 'HumanEval/0',
   'result': 'passed',
   'generated': '    for i in range(len(numbers)):\n        for j in range(i + 1, len(numbers)):\n            if abs(numbers[i] - numbers[j]) < threshold:\n                return True\n    return False',
   'elapsed_sec': 0.974153995513916},
  {'task_id': 'HumanEval/1',
   'result': 'passed',
   'generated': "    result = []\n    stack = []\n    current_group = []\n\n    for char in paren_string:\n        if char == ' ':\n            continue\n        if char == '(':\n            stack.append(char)\n            current_group.append(char)\n        elif char == ')':\n            stack.pop()\n            current_group.append(char)\n            if not stack:\n                result.append(''.join(current_group))\n                current_group = []\n\n    return result",
   'elapsed_sec': 1.7830970287322998},
  {'task_id': 'HumanEval/2',
   'result': 'passed',
   'generated': '    return number - int(number)',
   'elapsed_sec': 0.2911229133605957},
  {'task_id': 'HumanEval/3',
   'result': 'passed',
   'generated': '    balance = 0\n    for operation in operations:\n        balance += operation\n        if balance < 0:\n            return True\n    return False',
   'elapsed_sec': 0.632014274597168},
  {'task_id': 'HumanEval/4',
   'result': 'passed',
   'generated': '    if not numbers:\n        return 0.0\n    mean = sum(numbers) / len(numbers)\n    deviations = [abs(x - mean) for x in numbers]\n    mad = sum(deviations) / len(numbers)\n    return mad',
   'elapsed_sec': 0.9865560531616211},
  {'task_id': 'HumanEval/5',
   'result': 'passed',
   'generated': '    result = []\n    for i in range(len(numbers)):\n        result.append(numbers[i])\n        if i < len(numbers) - 1:\n            result.append(delimeter)\n    return result',
   'elapsed_sec': 0.8738322257995605},
  {'task_id': 'HumanEval/6',
   'result': 'passed',
   'generated': "    result = []\n    for group in paren_string.split():\n        max_depth = 0\n        depth = 0\n        for char in group:\n            if char == '(':\n                depth += 1\n                max_depth = max(max_depth, depth)\n            elif char == ')':\n                depth -= 1\n        result.append(max_depth)\n    return result",
   'elapsed_sec': 1.4653828144073486},
  {'task_id': 'HumanEval/7',
   'result': 'passed',
   'generated': '    return [s for s in strings if substring in s]',
   'elapsed_sec': 0.6003129482269287},
  {'task_id': 'HumanEval/8',
   'result': 'passed',
   'generated': '    sum_of_numbers = 0\n    product_of_numbers = 1\n    for number in numbers:\n        sum_of_numbers += number\n        product_of_numbers *= number\n    return sum_of_numbers, product_of_numbers',
   'elapsed_sec': 2.674668788909912},
  {'task_id': 'HumanEval/9',
   'result': 'passed',
   'generated': '    if not numbers:\n        return []\n\n    rolling_max_list = []\n    current_max = numbers[0]\n    for number in numbers:\n        current_max = max(current_max, number)\n        rolling_max_list.append(current_max)\n\n    return rolling_max_list',
   'elapsed_sec': 1.8882818222045898},
  {'task_id': 'HumanEval/10',
   'result': 'passed',
   'generated': '    if is_palindrome(string):\n        return string\n    for i in range(len(string)):\n        substring = string[i:]\n        if is_palindrome(substring):\n            return string + string[:i][::-1]\n    return string + string[::-1]\n\n\ndef main():\n    print(make_palindrome(\'\'))\n    print(make_palindrome(\'cat\'))\n    print(make_palindrome(\'cata\'))\n\n\nif __name__ == "__main__":\n    main()',
   'elapsed_sec': 3.2078499794006348},
  {'task_id': 'HumanEval/11',
   'result': 'passed',
   'generated': "    result = []\n    for i in range(len(a)):\n        if a[i] == b[i]:\n            result.append('0')\n        else:\n            result.append('1')\n    return ''.join(result)",
   'elapsed_sec': 1.4735419750213623},
  {'task_id': 'HumanEval/12',
   'result': 'passed',
   'generated': '    if not strings:\n        return None\n    longest_string = strings[0]\n    for string in strings:\n        if len(string) > len(longest_string):\n            longest_string = string\n    return longest_string',
   'elapsed_sec': 1.5042638778686523},
  {'task_id': 'HumanEval/13',
   'result': 'passed',
   'generated': '    while b:\n        a, b = b, a % b\n    return a',
   'elapsed_sec': 0.7924761772155762},
  {'task_id': 'HumanEval/14',
   'result': 'passed',
   'generated': '    return [string[:i] for i in range(1, len(string) + 1)]',
   'elapsed_sec': 0.7946600914001465},
  {'task_id': 'HumanEval/15',
   'result': 'passed',
   'generated': '    return " ".join(str(i) for i in range(n + 1))',
   'elapsed_sec': 0.7166552543640137},
  {'task_id': 'HumanEval/16',
   'result': 'passed',
   'generated': '    return len(set(string.lower()))',
   'elapsed_sec': 0.5351951122283936},
  {'task_id': 'HumanEval/17',
   'result': 'passed',
   'generated': '    pass\n\n# Solution:\n\nfrom typing import List\n\n\ndef parse_music(music_string: str) -> List[int]:\n    """ Input to this function is a string representing musical notes in a special ASCII format.\n    Your task is to parse this string and return list of integers corresponding to how many beats does each\n    not last.\n\n    Here is a legend:\n    \'o\' - whole note, lasts four beats\n    \'o|\' - half note, lasts two beats\n    \'.|\' - quater note, lasts one beat\n\n    >>> parse_music(\'o o| .| o| o| .| .| .| .| o o\')\n    [4, 2, 1, 2, 2, 1, 1, 1, 1, 4, 4]\n    """\n    notes = music_string.split()\n    beats = []\n    for note in notes:\n        if note == \'o\':\n            beats.append(4)\n        elif note == \'o|\':\n            beats.append(2)\n        elif note == \'.|\':\n            beats.append(1)\n    return beats',
   'elapsed_sec': 6.341253042221069},
  {'task_id': 'HumanEval/18',
   'result': 'passed',
   'generated': "    count = 0\n    start = 0\n    while True:\n        start = string.find(substring, start) + 1\n        if start > 0:\n            count += 1\n        else:\n            break\n    return count\n\n# Test cases\nprint(how_many_times('', 'a'))  # Expected output: 0\nprint(how_many_times('aaa', 'a'))  # Expected output: 3\nprint(how_many_times('aaaa', 'aa'))  # Expected output: 3",
   'elapsed_sec': 2.7903287410736084},
  {'task_id': 'HumanEval/19',
   'result': 'passed',
   'generated': "    num_dict = {'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 'six': 6, 'seven': 7, 'eight': 8, 'nine': 9}\n    num_list = numbers.split()\n    num_list.sort(key=lambda x: num_dict[x])\n    return ' '.join(num_list)",
   'elapsed_sec': 2.4978549480438232},
  {'task_id': 'HumanEval/20',
   'result': 'passed',
   'generated': "    min_diff = float('inf')\n    closest_pair = (0.0, 0.0)\n    numbers.sort()\n    for i in range(len(numbers) - 1):\n        diff = numbers[i + 1] - numbers[i]\n        if diff < min_diff:\n            min_diff = diff\n            closest_pair = (numbers[i], numbers[i + 1])\n    return closest_pair",
   'elapsed_sec': 2.732145071029663},
  {'task_id': 'HumanEval/21',
   'result': 'passed',
   'generated': '    min_val = min(numbers)\n    max_val = max(numbers)\n    return [(x - min_val) / (max_val - min_val) for x in numbers]',
   'elapsed_sec': 1.1414451599121094},
  {'task_id': 'HumanEval/22',
   'result': 'passed',
   'generated': '    return [value for value in values if isinstance(value, int)]',
   'elapsed_sec': 0.606719970703125},
  {'task_id': 'HumanEval/23',
   'result': 'passed',
   'generated': '    count = 0\n    for char in string:\n        count += 1\n    return count',
   'elapsed_sec': 0.7055017948150635},
  {'task_id': 'HumanEval/24',
   'result': 'passed',
   'generated': '    for i in range(n // 2, 0, -1):\n        if n % i == 0:\n            return i\n    return 1',
   'elapsed_sec': 0.9466259479522705},
  {'task_id': 'HumanEval/25',
   'result': 'passed',
   'generated': '    i = 2\n    factors = []\n    while i * i <= n:\n        if n % i:\n            i += 1\n        else:\n            n //= i\n            factors.append(i)\n    if n > 1:\n        factors.append(n)\n    return factors',
   'elapsed_sec': 1.8077709674835205},
  {'task_id': 'HumanEval/26',
   'result': 'failed',
   'generated': '    seen = {}\n    result = []\n    for number in numbers:\n        if number not in seen:\n            seen[number] = 1\n            result.append(number)\n        elif seen[number] == 1:\n            seen[number] += 1\n    return result\n\n\n# Test cases\nprint(remove_duplicates([1, 2, 3, 2, 4]))  # Expected output: [1, 3, 4]\nprint(remove_duplicates([1, 2, 3, 4, 5]))  # Expected output: [1, 2, 3, 4, 5]\nprint(remove_duplicates([1, 1, 1, 1, 1]))  # Expected output: []\nprint(remove_duplicates([1, 2, 2, 3, 3, 3, 4]))  # Expected output: [1, 4]',
   'elapsed_sec': 4.921519041061401},
  {'task_id': 'HumanEval/27',
   'result': 'passed',
   'generated': '    result = ""\n    for char in string:\n        if char.islower():\n            result += char.upper()\n        elif char.isupper():\n            result += char.lower()\n        else:\n            result += char\n    return result',
   'elapsed_sec': 1.2834570407867432},
  {'task_id': 'HumanEval/28',
   'result': 'passed',
   'generated': "    result = ''\n    for s in strings:\n        result += s\n    return result",
   'elapsed_sec': 0.6759347915649414},
  {'task_id': 'HumanEval/29',
   'result': 'passed',
   'generated': '    return [s for s in strings if s.startswith(prefix)]',
   'elapsed_sec': 0.5809838771820068},
  {'task_id': 'HumanEval/30',
   'result': 'passed',
   'generated': '    return [x for x in l if x > 0]',
   'elapsed_sec': 0.5655827522277832},
  {'task_id': 'HumanEval/31',
   'result': 'passed',
   'generated': '    if n <= 1:\n        return False\n    if n <= 3:\n        return True\n    if n % 2 == 0 or n % 3 == 0:\n        return False\n    i = 5\n    while i * i <= n:\n        if n % i == 0 or n % (i + 2) == 0:\n            return False\n        i += 6\n    return True',
   'elapsed_sec': 2.093729019165039},
  {'task_id': 'HumanEval/32',
   'result': 'failed',
   'generated': '    assert len(xs) % 2 == 0 and xs[-1] != 0, "xs must have even number of coefficients and largest non-zero coefficient"\n    low = -1000\n    high = 1000\n    while high - low > 1e-10:\n        mid = (low + high) / 2\n        if poly(xs, mid) > 0:\n            high = mid\n        else:\n            low = mid\n    return (low + high) / 2',
   'elapsed_sec': 2.993990898132324},
  {'task_id': 'HumanEval/33',
   'result': 'failed',
   'generated': '    pass\n\n\n\n```python\ndef sort_third(l: list):\n    third_elements = [l[i] for i in range(2, len(l), 3)]\n    third_elements.sort()\n    l_prime = l[:]\n    for i, value in zip(range(2, len(l), 3), third_elements):\n        l_prime[i] = value\n    return l_prime\n```',
   'elapsed_sec': 2.482187032699585},
  {'task_id': 'HumanEval/34',
   'result': 'passed',
   'generated': '    return sorted(set(l))',
   'elapsed_sec': 0.47545289993286133},
  {'task_id': 'HumanEval/35',
   'result': 'passed',
   'generated': '    pass\n\n\n\n```python\ndef max_element(l: list):\n    return max(l)\n```',
   'elapsed_sec': 0.7651729583740234},
  {'task_id': 'HumanEval/36',
   'result': 'failed',
   'generated': "    count = 0\n    for i in range(1, n):\n        if i % 11 == 0 or i % 13 == 0:\n            if '7' in str(i):\n                count += 1\n    return count",
   'elapsed_sec': 1.3615837097167969},
  {'task_id': 'HumanEval/37',
   'result': 'passed',
   'generated': '    evens = sorted([l[i] for i in range(0, len(l), 2)])\n    result = l[:]\n    even_index = 0\n    for i in range(0, len(l), 2):\n        result[i] = evens[even_index]\n        even_index += 1\n    return result',
   'elapsed_sec': 1.859715223312378},
  {'task_id': 'HumanEval/38',
   'result': 'passed',
   'generated': '    # split string to groups. Each of length 3.\n    groups = [s[(3 * i):min((3 * i + 3), len(s))] for i in range((len(s) + 2) // 3)]\n    # cycle elements in each group back. Unless group has fewer elements than 3.\n    groups = [(group[-1] + group[:-1]) if len(group) == 3 else group for group in groups]\n    return "".join(groups)',
   'elapsed_sec': 2.621687889099121},
  {'task_id': 'HumanEval/39',
   'result': 'passed',
   'generated': '    def is_prime(num):\n        if num <= 1:\n            return False\n        if num <= 3:\n            return True\n        if num % 2 == 0 or num % 3 == 0:\n            return False\n        i = 5\n        while i * i <= num:\n            if num % i == 0 or num % (i + 2) == 0:\n                return False\n            i += 6\n        return True\n\n    def fib(n):\n        a, b = 0, 1\n        for _ in range(n):\n            a, b = b, a + b\n        return a\n\n    count = 0\n    i = 0\n    while True:\n        fib_num = fib(i)\n        if is_prime(fib_num):\n            count += 1\n            if count == n:\n                return fib_num\n        i += 1\n\n# Example usage:\n# print(prime_fib(1))  # Output: 2\n# print(prime_fib(2))  # Output: 3\n# print(prime_fib(3))  # Output: 5\n# print(prime_fib(4))  # Output: 13\n# print(prime_fib(5))  # Output: 89',
   'elapsed_sec': 6.517544984817505},
  {'task_id': 'HumanEval/40',
   'result': 'failed',
   'generated': '    pass',
   'elapsed_sec': 11.344552755355835},
  {'task_id': 'HumanEval/41',
   'result': 'passed',
   'generated': '    return n * n\n\n# Example usage:\n# print(car_race_collision(3))  # Should output 9\n# print(car_race_collision(4))  # Should output 16\n# print(car_race_collision(5))  # Should output 25',
   'elapsed_sec': 1.5606131553649902},
  {'task_id': 'HumanEval/42',
   'result': 'passed',
   'generated': '    return [x + 1 for x in l]',
   'elapsed_sec': 0.5257318019866943},
  {'task_id': 'HumanEval/43',
   'result': 'passed',
   'generated': '    seen = set()\n    for num in l:\n        if -num in seen:\n            return True\n        seen.add(num)\n    return False',
   'elapsed_sec': 0.9297091960906982},
  {'task_id': 'HumanEval/44',
   'result': 'passed',
   'generated': "    if x == 0:\n        return '0'\n    digits = '0123456789'\n    result = ''\n    while x > 0:\n        result = digits[x % base] + result\n        x //= base\n    return result",
   'elapsed_sec': 1.4016308784484863},
  {'task_id': 'HumanEval/45',
   'result': 'passed',
   'generated': '    return (a * h) / 2',
   'elapsed_sec': 0.4687502384185791},
  {'task_id': 'HumanEval/46',
   'result': 'passed',
   'generated': '    if n == 0:\n        return 0\n    elif n == 1:\n        return 0\n    elif n == 2:\n        return 2\n    elif n == 3:\n        return 0\n    else:\n        a, b, c, d = 0, 0, 2, 0\n        for i in range(4, n + 1):\n            e = a + b + c + d\n            a, b, c, d = b, c, d, e\n        return d',
   'elapsed_sec': 2.6774208545684814},
  {'task_id': 'HumanEval/47',
   'result': 'passed',
   'generated': '    sorted_list = sorted(l)\n    n = len(sorted_list)\n    if n % 2 == 1:\n        return sorted_list[n // 2]\n    else:\n        return (sorted_list[n // 2 - 1] + sorted_list[n // 2]) / 2',
   'elapsed_sec': 1.6476998329162598},
  {'task_id': 'HumanEval/48',
   'result': 'failed',
   'generated': '    pass',
   'elapsed_sec': 10.770502090454102},
  {'task_id': 'HumanEval/49',
   'result': 'passed',
   'generated': '    return pow(2, n, p)',
   'elapsed_sec': 0.4843900203704834},
  {'task_id': 'HumanEval/50',
   'result': 'passed',
   'generated': '    return "".join([chr(((ord(ch) - 5 - ord("a")) % 26) + ord("a")) for ch in s])',
   'elapsed_sec': 0.87152099609375},
  {'task_id': 'HumanEval/51',
   'result': 'passed',
   'generated': "    vowels = 'aeiouAEIOU'\n    return ''.join(char for char in text if char not in vowels)",
   'elapsed_sec': 0.7885787487030029},
  {'task_id': 'HumanEval/52',
   'result': 'passed',
   'generated': '    pass\n\n\n\n```python\ndef below_threshold(l: list, t: int):\n    return all(x < t for x in l)\n```',
   'elapsed_sec': 0.9139893054962158},
  {'task_id': 'HumanEval/53',
   'result': 'passed',
   'generated': '    return x + y',
   'elapsed_sec': 10.713858127593994},
  {'task_id': 'HumanEval/54',
   'result': 'failed',
   'generated': '    return sorted(s0) == sorted(s1)',
   'elapsed_sec': 0.589198112487793},
  {'task_id': 'HumanEval/55',
   'result': 'passed',
   'generated': '    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a',
   'elapsed_sec': 9.877357006072998},
  {'task_id': 'HumanEval/56',
   'result': 'passed',
   'generated': '    stack = []\n    for bracket in brackets:\n        if bracket == "<":\n            stack.append(bracket)\n        elif bracket == ">":\n            if not stack:\n                return False\n            stack.pop()\n    return not stack',
   'elapsed_sec': 1.1770761013031006},
  {'task_id': 'HumanEval/57',
   'result': 'failed',
   'generated': '    increasing = all(x < y for x, y in zip(l, l[1:]))\n    decreasing = all(x > y for x, y in zip(l, l[1:]))\n    return increasing or decreasing',
   'elapsed_sec': 1.1385719776153564},
  {'task_id': 'HumanEval/58',
   'result': 'passed',
   'generated': '    return sorted(set(l1) & set(l2))',
   'elapsed_sec': 0.5633540153503418},
  {'task_id': 'HumanEval/59',
   'result': 'passed',
   'generated': '    i = 2\n    while i * i <= n:\n        if n % i:\n            i += 1\n        else:\n            n //= i\n    return n',
   'elapsed_sec': 0.9738380908966064},
  {'task_id': 'HumanEval/60',
   'result': 'passed',
   'generated': '    return n * (n + 1) // 2',
   'elapsed_sec': 0.5393772125244141},
  {'task_id': 'HumanEval/61',
   'result': 'passed',
   'generated': '    stack = []\n    for bracket in brackets:\n        if bracket == "(":\n            stack.append(bracket)\n        elif bracket == ")":\n            if not stack:\n                return False\n            stack.pop()\n    return not stack',
   'elapsed_sec': 1.1223058700561523},
  {'task_id': 'HumanEval/62',
   'result': 'failed',
   'generated': '    pass',
   'elapsed_sec': 9.793068885803223},
  {'task_id': 'HumanEval/63',
   'result': 'passed',
   'generated': '    if n == 0 or n == 1:\n        return 0\n    elif n == 2:\n        return 1\n    else:\n        a, b, c = 0, 0, 1\n        for i in range(3, n + 1):\n            a, b, c = b, c, a + b + c\n        return c',
   'elapsed_sec': 1.6893959045410156},
  {'task_id': 'HumanEval/64',
   'result': 'error: SyntaxError: invalid syntax. Perhaps you forgot a comma?',

# Sensitivity Experiments
Now that we've got some baseline results from our three models, it's time to perform sensitivity analysis.

Next steps:
1) Build a clean summary table from timestamped fp16/q8/q4 run files
2) Set the reference baseline for notebook 07
3) Do one ablation loop step (claim -> run -> record), and repeat

In [20]:
pat = re.compile(r"^07_(fp16|q8_0|q4_k_m)_humaneval_(\d{8}T\d{6}Z)\.json$")

rows = []
for p in RESULTS_DIR.glob("07_*_humaneval_*.json"):
    m = pat.match(p.name)
    if not m:
        continue
    model_key, run_ts = m.group(1), m.group(2)
    with p.open() as f:
        d = json.load(f)
    rows.append({
        "model_key": model_key,
        "run_ts": run_ts,
        "pass_at_1_percent": d.get("candidate_pass_at_1_percent"),
        "n_total": d.get("n_total"),
        "path": str(p),
    })

df = pd.DataFrame(rows).sort_values(["model_key", "run_ts"])
latest = df.groupby("model_key", as_index=False).tail(1).sort_values("pass_at_1_percent", ascending=False)

print("Latest run per model:")
display(latest[["model_key", "run_ts", "pass_at_1_percent", "n_total"]])

latest_path_map = dict(zip(latest["model_key"], latest["path"]))
print("\nLatest file map:")
print(latest_path_map)

Latest run per model:

  model_key            run_ts  pass_at_1_percent  n_total
1    q4_k_m  20260511T130907Z          75.000000      164
2      fp16  20260511T132341Z          72.560976      164
0      q8_0  20260511T131758Z          71.951220      164

Latest file map:
{'q4_k_m': '/Users/jarrett/dev/quantization-study/results/07_q4_k_m_humaneval_20260511T130907Z.json', 'fp16': '/Users/jarrett/dev/quantization-study/results/07_fp16_humaneval_20260511T132341Z.json', 'q8_0': '/Users/jarrett/dev/quantization-study/results/07_q8_0_humaneval_20260511T131758Z.json'}

In [21]:
# Step 2: save a notebook-07 parity baseline summary (llama.cpp-only reference).
baseline_07 = {
    "timestamp_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
    "notebook": "07_sensitivity_analysis",
    "harness": {
        "backend": "llama_cpp",
        "dataset": "openai/openai_humaneval",
        "n_total": 164,
        "notes": "Parity runs under same backend/settings; use fp16 here as Notebook-07 reference, not notebook-03 transformers bsaeline.",
    },
    "latest_runs": {
        "q4_k_m": {
            "run_ts": "20260407T063833Z",
            "pass_at_1_percent": 75.0,
            "path": str(RESULTS_DIR / "07_q4_k_m_humaneval_20260407T063833Z.json")
        },
        "fp16": {
            "run_ts": "20260407T064700Z",
            "pass_at_1_percent": 72.560976,
            "path": str(RESULTS_DIR / "07_fp16_humaneval_20260407T064700Z.json"),
        },
        "q8_0": {
            "run_ts": "20260407T064158Z",
            "pass_at_1_percent": 71.951220,
        },
    },
    "ranking": ["q4_k_m", "fp16", "q8_0"],
}

out_path = RESULTS_DIR / "07_parity_baseline_summary.json"
with out_path.open("w") as f:
    json.dump(baseline_07, f, indent=2)

print(f"Saved: {out_path}")
print("Reference fp16 pass@1 for Notebook-07 sensitivity deltas:", baseline_07["latest_runs"]["fp16"]["pass_at_1_percent"])

Saved: /Users/jarrett/dev/quantization-study/results/07_parity_baseline_summary.json
Reference fp16 pass@1 for Notebook-07 sensitivity deltas: 72.560976

In [22]:
# Step 3: update sensitivity manifest reference baseline to notebook-07 llama.cpp fp16 parity baseline.
PARITY_PATH = RESULTS_DIR / "07_parity_baseline_summary.json"

with MANIFEST_PATH.open() as f:
    manifest = json.load(f)

with PARITY_PATH.open() as f:
    parity = json.load(f)

new_ref = float(parity["latest_runs"]["fp16"]["pass_at_1_percent"])
old_ref = float(manifest["reference"]["baseline_pass_at_1_percent"])

manifest["reference"]["baseline_pass_at_1_percent"] = new_ref
manifest["reference"]["baseline_source"] = str(PARITY_PATH)
manifest["reference"]["baseline_kind"] = "fp16_llama_cpp_parity"
manifest["reference"]["updated_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()

for section in ["layer", "expert"]:
    for a in manifest["ablations"][section]:
        cand = a.get("candidate_pass_at_1_percent")
        if cand is not None:
            delta = new_ref - float(cand)
            a["delta_pass_at_1_percent"] = delta
            a["relative_drop"] = (delta / new_ref) if new_ref else None

with MANIFEST_PATH.open("w") as f:
    json.dump(manifest, f, indent=2)

print(f"Updated manifest baseline: {old_ref:.6f} -> {new_ref:.6f}")

Updated manifest baseline: 60.365854 -> 72.560976

In [23]:
# Step 4: claim next pending ablation
# Mark stale in_progress as completed if it already has a recorded candidate score, then claim next pending.
with MANIFEST_PATH.open() as f:
    m = json.load(f)

all_items = m["ablations"]["layer"] + m["ablations"]["expert"]

# close stale run if score already exists
for a in all_items:
    if a["status"] == "in_progress" and a.get("candidate_pass_at_1_percent") is not None:
        a["status"] = "completed"
        a["completed_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()

# claim next pending
active = [a for a in all_items if a["status"] == "in_progress"]
if active:
    print("Still in progress:", active[0]["ablation_id"])
else:
    pending = [a for a in all_items if a["status"] == "pending"]
    if not pending:
        print("No pending ablations left.")
    else:
        nxt = pending[0]
        nxt["status"] = "in_progress"
        nxt["started_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()
        print("Claimed:", nxt["ablation_id"], "|", nxt["kind"])

with MANIFEST_PATH.open("w") as f:
    json.dump(m, f,)

Claimed: layer_group_01 | layer_group

In [24]:
# Cancel stale active ablation and claim next pending.                                                                                                                                                                                         
with MANIFEST_PATH.open() as f:                                                                                        
    m = json.load(f)                                                                                                   
                                                                                                                        
all_items = m["ablations"]["layer"] + m["ablations"]["expert"]                                                         
                                                                                                                        
# Cancel any currently in-progress item (stale pre-parity run).                                                        
for a in all_items:                                                                                                    
    if a["status"] == "in_progress":                                                                                   
        a["status"] = "cancelled"                                                                                      
        a["cancelled_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()                                           
        a["notes"] = (a.get("notes", "") + " cancelled after harness/baseline reset").strip()                          
                                                                                                                        
# Claim next pending.                                                                                                  
pending = [a for a in all_items if a["status"] == "pending"]                                                           
if not pending:                                                                                                        
    print("No pending ablations left.")                                                                                
else:                                                                                                                  
    nxt = pending[0]                                                                                                   
    nxt["status"] = "in_progress"                                                                                      
    nxt["started_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()                                               
    print("Claimed:", nxt["ablation_id"], "|", nxt["kind"], "| layers:", nxt["target_layers"], "| experts:",           
nxt["target_experts"])                                                                                                 
                                                                                                                        
with MANIFEST_PATH.open("w") as f:                                                                                     
    json.dump(m, f, indent=2)

Claimed: layer_group_02 | layer_group | layers: [6, 7, 8] | experts: None